# Site setings
name: 'Sarah Ziselman'
description: 'Robotics Engineer'
# Sidebar about text
site_description: 
logo:
favicon: 'assets/images/favicon.ico'
baseurl: sziselman
production_url: https://forma.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: sarahziselman2020@u.northwestern.edu
contact_page_description: "Forma theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter:
facebook:
github: 'sziselman'
codepen:
dribbble:
medium:
instagram:
pinterest:
linkedin: 'sarah-ziselman'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-author-page

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
